#!/bin/bash
# GKE Deployment Script
# Builds images, pushes to GCR, generates config, and deploys with Helm

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║                                                            ║${NC}"
echo -e "${BLUE}║        GKE Deployment - Build, Push & Deploy               ║${NC}"
echo -e "${BLUE}║                                                            ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Add gcloud to PATH
export PATH="$HOME/google-cloud-sdk/bin:/opt/homebrew/bin:$PATH"

# Get current GCP project
PROJECT=$(gcloud config get-value project 2>/dev/null)
if [ -z "$PROJECT" ]; then
    echo -e "${RED}✗ No GCP project set${NC}"
    echo "Run: gcloud config set project PROJECT_ID"
    exit 1
fi

# Get cluster info
CLUSTER_NAME=${GKE_CLUSTER_NAME:-wander-cluster}
ZONE=${GKE_ZONE:-us-central1-a}

echo -e "${CYAN}Configuration:${NC}"
echo -e "  Project: ${PROJECT}"
echo -e "  Cluster: ${CLUSTER_NAME}"
echo -e "  Zone: ${ZONE}"
echo -e "  Registry: gcr.io/${PROJECT}"
echo ""

# Build version tag
VERSION=${VERSION:-$(date +%Y%m%d-%H%M%S)}
echo -e "${CYAN}Build version: ${VERSION}${NC}"
echo ""

# Enable Cloud Build API
echo -e "${YELLOW}Ensuring Cloud Build API is enabled...${NC}"
gcloud services enable cloudbuild.googleapis.com --project="${PROJECT}" 2>/dev/null || true
echo -e "${GREEN}✓ Cloud Build API enabled${NC}"

echo -e "${YELLOW}Building API image in Google Cloud (native AMD64)...${NC}"
echo -e "${CYAN}This builds in the cloud, so it's the correct architecture${NC}"
gcloud builds submit ./api \
    --config=./api/cloudbuild.yaml \
    --substitutions=_IMAGE_NAME="gcr.io/${PROJECT}/wander-api:${VERSION}" \
    --timeout=10m

# Tag as latest
gcloud container images add-tag \
    "gcr.io/${PROJECT}/wander-api:${VERSION}" \
    "gcr.io/${PROJECT}/wander-api:latest" \
    --quiet

echo -e "${GREEN}✓ API image built and pushed${NC}"
echo ""

echo -e "${YELLOW}Building Frontend image in Google Cloud (native AMD64)...${NC}"
gcloud builds submit ./frontend \
    --config=./frontend/cloudbuild.yaml \
    --substitutions=_IMAGE_NAME="gcr.io/${PROJECT}/wander-frontend:${VERSION}" \
    --timeout=10m

# Tag as latest
gcloud container images add-tag \
    "gcr.io/${PROJECT}/wander-frontend:${VERSION}" \
    "gcr.io/${PROJECT}/wander-frontend:latest" \
    --quiet

echo -e "${GREEN}✓ Frontend image built and pushed${NC}"
echo ""

# Generate secure passwords
POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)
REDIS_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)

echo -e "${YELLOW}Generated secure passwords for database and cache${NC}"
echo ""

# Generate values-gke.yaml
echo -e "${YELLOW}Generating GKE values file...${NC}"
cat > k8s/charts/wander/values-gke.yaml <<EOF
# Google Kubernetes Engine (GKE) Configuration
# Auto-generated by gke-deploy.sh on $(date)
# Project: ${PROJECT}

## API Configuration
api:
  replicaCount: 2

  image:
    repository: gcr.io/${PROJECT}/wander-api
    tag: ${VERSION}
    pullPolicy: Always

  service:
    type: LoadBalancer
    port: 8000

  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  env:
    - name: NODE_ENV
      value: "production"
    - name: API_PORT
      value: "8000"

## Frontend Configuration
frontend:
  replicaCount: 2

  image:
    repository: gcr.io/${PROJECT}/wander-frontend
    tag: ${VERSION}
    pullPolicy: Always

  service:
    type: LoadBalancer
    port: 80

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  env:
    - name: NODE_ENV
      value: "production"
    - name: VITE_API_URL
      value: "http://wander-api:8000"

## PostgreSQL Configuration (Bitnami)
postgresql:
  enabled: true
  image:
    tag: "16.6.0-debian-12-r5"
  auth:
    username: wander
    password: ${POSTGRES_PASSWORD}
    database: wander_prod

  primary:
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

    persistence:
      enabled: true
      size: 10Gi
      storageClass: standard-rwo

## Redis Configuration (Bitnami)
redis:
  enabled: true
  image:
    tag: "7.4.2-debian-12-r3"
  auth:
    password: ${REDIS_PASSWORD}

  master:
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

    persistence:
      enabled: true
      size: 5Gi
      storageClass: standard-rwo

  replica:
    replicaCount: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

    persistence:
      enabled: true
      size: 5Gi
      storageClass: standard-rwo

## Ingress Configuration
ingress:
  enabled: false  # Using LoadBalancer for simplicity

## ServiceAccount
serviceAccount:
  create: true
  name: wander-gke

## Autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

## Security Context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
EOF

echo -e "${GREEN}✓ Generated k8s/charts/wander/values-gke.yaml${NC}"
echo ""

# Add Bitnami Helm repo
echo -e "${YELLOW}Adding Bitnami Helm repository...${NC}"
helm repo add bitnami https://charts.bitnami.com/bitnami 2>/dev/null || true
helm repo update
echo -e "${GREEN}✓ Helm repo updated${NC}"
echo ""

# Build Helm dependencies
echo -e "${YELLOW}Fetching Helm chart dependencies...${NC}"
cd k8s/charts/wander
helm dependency build
echo -e "${GREEN}✓ Dependencies fetched${NC}"
echo ""

# Deploy with Helm
echo -e "${YELLOW}Deploying to GKE with Helm...${NC}"
echo -e "${CYAN}This will take 5-8 minutes on first deploy:${NC}"
echo -e "  - Pulling images from GCR"
echo -e "  - Creating PostgreSQL with persistent volume"
echo -e "  - Creating Redis with persistent volume"
echo -e "  - Starting API and Frontend pods"
echo -e "  - Provisioning LoadBalancer IPs"
echo -e "  - Waiting for all health checks to pass"
echo ""
echo -e "${CYAN}You can monitor progress in another terminal:${NC}"
echo -e "  kubectl get pods -n wander -w"
echo ""

helm upgrade --install wander . \
    -f values-gke.yaml \
    --namespace wander \
    --create-namespace \
    --wait \
    --timeout 15m

echo -e "${GREEN}✓ Deployed to GKE${NC}"
echo ""

# Get service IPs
echo -e "${YELLOW}Waiting for LoadBalancer IPs...${NC}"
echo -e "${CYAN}This may take 2-3 minutes...${NC}"
echo ""

# Wait for API LoadBalancer
kubectl wait --for=jsonpath='{.status.loadBalancer.ingress}' \
    service/wander-api -n wander --timeout=300s 2>/dev/null || true

# Wait for Frontend LoadBalancer
kubectl wait --for=jsonpath='{.status.loadBalancer.ingress}' \
    service/wander-frontend -n wander --timeout=300s 2>/dev/null || true

# Display service info
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Deployment Complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}Service Information:${NC}"
kubectl get svc -n wander

echo ""
API_IP=$(kubectl get svc wander-api -n wander -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "pending")
FRONTEND_IP=$(kubectl get svc wander-frontend -n wander -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "pending")

echo -e "${BLUE}Access URLs:${NC}"
if [ "$API_IP" != "pending" ] && [ -n "$API_IP" ]; then
    echo -e "  API: ${CYAN}http://${API_IP}:8000${NC}"
    echo -e "  API Health: ${CYAN}http://${API_IP}:8000/health${NC}"
else
    echo -e "  API: ${YELLOW}Waiting for IP...${NC}"
fi

if [ "$FRONTEND_IP" != "pending" ] && [ -n "$FRONTEND_IP" ]; then
    echo -e "  Frontend: ${CYAN}http://${FRONTEND_IP}${NC}"
else
    echo -e "  Frontend: ${YELLOW}Waiting for IP...${NC}"
fi

echo ""
echo -e "${YELLOW}Credentials saved to: k8s/charts/wander/values-gke.yaml${NC}"
echo -e "${YELLOW}⚠  Keep this file secure - it contains database passwords${NC}"
echo ""
echo -e "${BLUE}Useful commands:${NC}"
echo -e "  View pods: ${CYAN}kubectl get pods -n wander${NC}"
echo -e "  View logs: ${CYAN}kubectl logs -f deployment/wander-api -n wander${NC}"
echo -e "  Get IPs again: ${CYAN}kubectl get svc -n wander${NC}"
echo ""
echo -e "${YELLOW}⚠  Remember to delete cluster when done: ${CYAN}make gke-teardown${NC}"
echo ""
